import LiteEFG as LiteEFG
from __future__ import annotations
import numpy as np
__all__ = ['LiteEFG', 'graph', 'np']
class graph(LiteEFG._LiteEFG.Graph):
    def __init__(self, eta = 0.001, gamma = 0.0005):
        ...
    def _update(self, gradient, upd_u, ref_u):
        ...
    def current_strategy(self) -> LiteEFG._LiteEFG.GraphNode:
        ...
    def update_graph(self, env: LiteEFG._LiteEFG.Environment) -> None:
        ...
