from __future__ import annotations
import typing
import LiteEFG as leg
from LiteEFG.baselines.baseline import _baseline
__all__ = ['leg', 'graph']
class graph(leg.baselines.baseline._baseline):
    def __init__(self, eta = 0.1, regularizer: typing.Literal['Euclidean', 'Entropy'] = 'Euclidean', weighted = False):
        ...
    def _get_ev(self, gradient, ev, strategy, ref_strategy):
        ...
    def _update(self, gradient, upd_u, ref_u):
        ...
    def current_strategy(self) -> leg._LiteEFG.GraphNode:
        ...
    def update_graph(self, env: leg._LiteEFG.Environment) -> None:
        ...
