from __future__ import annotations
import typing
import LiteEFG as leg
from LiteEFG.baselines.baseline import _baseline
__all__ = ['leg', 'graph']
class graph(leg.baselines.baseline._baseline):
    def __init__(self, eta = 0.1, tau = 0.001, gamma = 0.001, regularizer: typing.Literal['Euclidean', 'Entropy'] = 'Entropy', feedback = 'Q', weighted = False):
        ...
    def _full_information(self):
        ...
    def _outcome_sampling(self):
        ...
    def _update(self, upd_u, ref_u, gradient):
        ...
    def current_strategy(self) -> leg._LiteEFG.GraphNode:
        ...
    def update_graph(self, env: leg._LiteEFG.Environment) -> None:
        ...
