from __future__ import annotations

import os
from typing import Any, Mapping, Sequence

from ._LiteEFG import Graph, GraphNode

__all__ = ["CppEnv", "compile_cpp_game"]

class _CppEnvironment:
    @property
    def player_num(self) -> int: ...
    def set_graph(self, graph: Graph) -> None: ...
    def update(self, strategy: GraphNode | list[GraphNode], upd_player: int = -1, upd_color: list[int] = ..., traverse_type: str = "default") -> None: ...
    def update_strategy(self, strategy: GraphNode | list[GraphNode], update_best: bool = False) -> None: ...
    def exploitability(self, strategy: GraphNode | list[GraphNode], type_name: str = "default") -> list[float]: ...
    def utility(self, strategy: GraphNode | list[GraphNode], type_name: str = "default") -> list[float]: ...
    def evaluate(self, strategy: GraphNode | list[GraphNode], type_name: str = "default") -> dict[str, Any]: ...
    def get_strategy(self, player: int, strategy: GraphNode, type_name: str = "default") -> list[tuple[bytes, list[float]]]: ...
    def get_value(self, player: int, node: GraphNode) -> list[tuple[bytes, list[float]]]: ...
    def stats(self) -> dict[str, Any]: ...
    def inspect(self, actions: Sequence[int]) -> dict[str, Any]: ...

def compile_cpp_game(source: str | os.PathLike[str], cache_dir: str | os.PathLike[str] | None = None, extra_compile_args: Sequence[str] = ()) -> str: ...
def CppEnv(source: str | os.PathLike[str], parameters: Mapping[str, Any] | None = None, traverse_type: str = "External", cache_dir: str | os.PathLike[str] | None = None, extra_compile_args: Sequence[str] = ()) -> _CppEnvironment: ...
