from LiteEFG import _LiteEFG
from LiteEFG._LiteEFG import GraphNode
from __future__ import annotations
__all__: list = ['uniform', 'normal', 'exponential']
def _get_binding(name: str):
    ...
def exponential(node: GraphNode, lambda_: float = 1.0) -> GraphNode:
    ...
def normal(node: GraphNode, mean: float = 0.0, stddev: float = 1.0) -> GraphNode:
    ...
def uniform(node: GraphNode, lower: float = 0.0, upper: float = 1.0) -> GraphNode:
    ...
